[package]
name = "lps22df"
version = "0.1.0"
edition = "2021"
description = "This crate provides a platform agnostic driver for the ST LPS22DF temperature sensor."
readme = "README.md"
license = "BSD 3-Clause License"
exclude = [
    "target/debug/*"
    ]
keywords = ["st", "mems", "driver", "embedded-hal", "pressure-temperature"]
[dependencies]
embedded-hal = "1.0.0"
bitfield = "0.15.0"
generic-bus = {git = "https://gitlab.di.unimi.it/andrea.tambani/generic-bus"}